"""Create a baseline migrations

Revision ID: 60f17ffe2abb
Revises: ec496bf5b60e
Create Date: 2024-02-06 12:09:13.639226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60f17ffe2abb'
down_revision: Union[str, None] = 'ec496bf5b60e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.String(length=2), nullable=False),
    sa.Column('name_english', sa.String(), nullable=False),
    sa.Column('name_native', sa.String(), nullable=False),
    sa.Column('ema_since', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sorting_name', sa.String(), nullable=False),
    sa.Column('calling_name', sa.String(), nullable=False),
    sa.Column('old_ema_id', sa.String(length=8), nullable=False),
    sa.Column('country_id', sa.String(length=2), nullable=False),
    sa.Column('local_club', sa.String(), nullable=True),
    sa.Column('local_club_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tournament',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mers', sa.Float(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('ruleset', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('effective_end_date', sa.DateTime(), nullable=False),
    sa.Column('country_id', sa.String(length=2), nullable=False),
    sa.Column('nPlayers', sa.Integer(), nullable=False),
    sa.Column('nEMACountries', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_x_tournament',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('actual_rank', sa.Integer(), nullable=False),
    sa.Column('base_rank', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.String(length=2), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ),
    sa.PrimaryKeyConstraint('player_id', 'tournament_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_x_tournament')
    op.drop_table('tournament')
    op.drop_table('player')
    op.drop_table('country')
    # ### end Alembic commands ###
